name = "caat-powerbot"
compatibility_date = "2026-07-23"
compatibility_flags = ["nodejs_compat"]

# Point to custom worker entry point
main = "./custom-worker.ts"

[assets]
directory = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "solar-db"
database_id = "cf2b908f-d38d-47a2-8e7b-a14ccc21c80b"
migrations_dir = "db/migrations"

[triggers]
# Runs every day at 18:00 UTC (11:30 PM IST)
crons = ["0 18 * * *"]
