"use client";
import { FormEvent, useEffect, useState } from "react";
import { Card, Button } from "@/components/ui";
import { inr } from "@/lib/utils";

type Lead = { id: string; name: string; phone: string; email: string; city: string; monthly_bill: number; status: string };
const statuses = ["new", "called", "site_visit", "proposal_sent", "won", "lost"];

export default function Admin() {
  const [logged, setLogged] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [leads, setLeads] = useState<Lead[]>([]); const [search, setSearch] = useState(""); const [settings, setSettings] = useState<Record<string, number>>({});
  const login = async (event: FormEvent) => { event.preventDefault(); setError(""); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) { setError("Email or password is incorrect."); return; } setLogged(true); };
  const load = async (query = "") => { const response = await fetch(`/api/admin/leads?search=${encodeURIComponent(query)}`); if (response.ok) setLeads((await response.json()).data.items); const settingsResponse = await fetch("/api/settings"); if (settingsResponse.ok) setSettings((await settingsResponse.json()).data); };
  useEffect(() => { if (logged) void load(); }, [logged]);
  const updateStatus = async (leadId: string, status: string) => { await fetch("/api/lead/status", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId, status }) }); await load(search); };
  const saveSettings = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); };
  const exportCsv = () => { const csv = ["Name,Phone,Email,City,Monthly Bill,Status", ...leads.map(lead => [lead.name, lead.phone, lead.email, lead.city, lead.monthly_bill, lead.status].map(value => `"${String(value ?? "").replaceAll('"', '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "caat-powerbot-leads.csv"; link.click(); URL.revokeObjectURL(url); };
  if (!logged) return <main className="grid min-h-screen place-items-center p-6"><Card className="w-full max-w-md"><p className="font-black text-teal">caat powerbot / admin</p><h1 className="mt-6 text-3xl font-black">Welcome back.</h1><form onSubmit={login} className="mt-6 space-y-3"><input className="w-full rounded-2xl border p-3" placeholder="Email" type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} required /><input className="w-full rounded-2xl border p-3" placeholder="Password" type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} required /><button className="w-full rounded-full bg-ink p-3 font-bold text-white">Sign in</button>{error && <p className="text-sm text-red-600">{error}</p>}</form></Card></main>;
  return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><p className="font-black text-teal">caat powerbot / admin</p><h1 className="mt-2 text-4xl font-black">Lead operations.</h1></div><button onClick={() => setLogged(false)} className="text-sm font-bold">Sign out</button></div><div className="mt-10 grid gap-4 md:grid-cols-4">{[["Today’s leads", leads.length.toString()], ["Total leads", leads.length.toString()], ["Revenue estimate", inr(leads.reduce((total, lead) => total + Number(lead.monthly_bill || 0) * 40, 0))], ["Site visits", leads.filter(lead => lead.status === "site_visit").length.toString()]].map(([label, value]) => <Card key={label}><p className="text-sm text-ink/50">{label}</p><b className="mt-3 block text-3xl">{value}</b></Card>)}</div><Card className="mt-6 overflow-x-auto"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Leads</h2><div className="flex gap-2"><input className="rounded-full border px-4 py-2 text-sm" placeholder="Search leads" value={search} onChange={event => setSearch(event.target.value)} onKeyDown={event => { if (event.key === "Enter") void load(search); }} /><Button variant="outline" onClick={exportCsv}>Export CSV</Button></div></div><table className="mt-6 w-full min-w-[720px] text-left text-sm"><thead className="text-ink/50"><tr><th className="pb-3">Customer</th><th>City</th><th>Monthly bill</th><th>Status</th></tr></thead><tbody>{leads.map(lead => <tr key={lead.id} className="border-t border-ink/10"><td className="py-4"><b>{lead.name}</b><br /><span className="text-xs text-ink/50">{lead.phone} · {lead.email}</span></td><td>{lead.city}</td><td>{inr(Number(lead.monthly_bill))}</td><td><select className="rounded-full border px-3 py-2 text-xs" value={lead.status} onChange={event => void updateStatus(lead.id, event.target.value)}>{statuses.map(status => <option value={status} key={status}>{status.replaceAll("_", " ")}</option>)}</select></td></tr>)}</tbody></table>{leads.length === 0 && <p className="py-10 text-center text-sm text-ink/50">No persisted leads yet. Submit a public quote to populate this table.</p>}</Card><Card className="mt-6"><h2 className="text-xl font-black">Quote settings</h2><form onSubmit={saveSettings} className="mt-6 grid gap-4 md:grid-cols-3">{Object.entries(settings).map(([key, value]) => <label key={key} className="text-sm"><span className="mb-2 block font-bold">{key.replaceAll("_", " ")}</span><input className="w-full rounded-2xl border p-3" type="number" step="any" value={value ?? ""} onChange={event => setSettings(current => ({ ...current, [key]: Number(event.target.value) }))} /></label>)}<div className="md:col-span-3"><Button>Save settings</Button></div></form></Card></div></main>;
}
