import { describe, expect, it } from "vitest";
import { hashPassword, verifyPassword } from "../lib/password";

describe("admin password hashing", () => {
  it("verifies a password generated by the application", async () => {
    const hash = await hashPassword("correct-test-password");
    await expect(verifyPassword("correct-test-password", hash)).resolves.toBe(true);
    await expect(verifyPassword("wrong-password", hash)).resolves.toBe(false);
  });
});
