import Link from "next/link";
import { ArrowUpRight, Check, Sun, Zap } from "lucide-react";
import { Button, Card } from "./ui";
const benefits = ["Lower electricity bills", "25-year clean energy returns", "End-to-end EPC support", "Smart, future-ready systems"];
export function Landing() { return <main>
  <nav className="container-wide flex items-center justify-between py-6"><Link href="/" className="text-xl font-black tracking-tight">caat <span className="text-teal">powerbot</span><span className="text-lime">.</span></Link><div className="hidden gap-7 text-sm font-semibold md:flex"><a href="#why">Why solar</a><a href="#process">Process</a><a href="#faq">FAQ</a></div><Link href="/quote"><Button>Get instant quote <ArrowUpRight className="ml-1 inline" size={16}/></Button></Link></nav>
  <section className="grid-lines overflow-hidden"><div className="container-wide grid min-h-[600px] items-center gap-10 py-16 lg:grid-cols-[1.05fr_.95fr]"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-teal/20 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-teal"><Sun size={15}/> India&apos;s smarter energy switch</p><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-.05em] md:text-7xl">Calculate your solar savings <span className="text-teal">in 2 minutes.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-ink/65">See how much you can save, the right system for your roof, and your path to energy independence.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/quote"><Button>Get instant quote <ArrowUpRight className="ml-1 inline" size={17}/></Button></Link><a href="#contact"><Button variant="outline">Book site visit</Button></a></div><div className="mt-8 flex items-center gap-3 text-sm font-semibold"><div className="flex -space-x-2"><span className="h-8 w-8 rounded-full bg-orange-200"/><span className="h-8 w-8 rounded-full bg-teal/40"/><span className="h-8 w-8 rounded-full bg-lime"/></div> Trusted by energy-conscious families</div></div><div className="relative"><div className="absolute -right-20 -top-10 h-72 w-72 rounded-full bg-lime/60 blur-3xl"/><Card className="relative rotate-2 border border-ink/5 bg-ink text-cream"><div className="flex items-center justify-between"><span className="text-sm text-cream/60">Your solar snapshot</span><Zap className="text-lime"/></div><div className="mt-12 text-6xl font-black">₹8,420<span className="text-xl text-cream/50">/mo</span></div><p className="mt-2 text-cream/60">Potential monthly savings</p><div className="mt-12 h-32 rounded-2xl bg-gradient-to-t from-teal/50 to-lime/60 p-4"><div className="flex h-full items-end gap-2">{[30,42,55,48,70,82,95].map((h,i)=><div key={i} className="flex-1 rounded-t bg-lime/80" style={{height:`${h}%`}}/>)}</div></div><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="rounded-2xl bg-white/10 p-4"><b>6.6 kW</b><br/><span className="text-cream/50">Recommended</span></div><div className="rounded-2xl bg-white/10 p-4"><b>₹25.2L</b><br/><span className="text-cream/50">25-year value</span></div></div></Card></div></div></section>
  <section id="why" className="container-wide py-24"><p className="font-bold uppercase tracking-[.18em] text-teal">Why caat powerbot</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-tight md:text-5xl">A clearer way to make a big energy decision.</h2><div className="mt-10 grid gap-4 md:grid-cols-4">{benefits.map((b,i)=><Card key={b} className={i===1?"bg-lime":""}><div className="mb-12 text-3xl font-black">0{i+1}</div><Check className="text-teal"/><h3 className="mt-4 font-bold">{b}</h3></Card>)}</div></section>
  <section id="process" className="bg-ink py-24 text-cream"><div className="container-wide"><p className="font-bold uppercase tracking-[.18em] text-lime">How it works</p><div className="mt-8 grid gap-10 md:grid-cols-3">{[["01","Tell us about your home","A two-minute form gives us the context we need."],["02","Get your solar snapshot","Our calculator models your system, savings and payback."],["03","Make it real","Book a free survey and let our EPC team take it forward."]].map(([n,t,d])=><div key={n} className="border-t border-white/20 pt-5"><span className="text-lime">{n}</span><h3 className="mt-10 text-2xl font-black">{t}</h3><p className="mt-3 text-cream/60">{d}</p></div>)}</div></div></section>
  <section id="faq" className="container-wide py-24"><p className="font-bold uppercase tracking-[.18em] text-teal">FAQ</p><div className="mt-8 grid gap-4 md:grid-cols-2">{["How accurate is my quote?","What happens after I submit?","Can solar work on a rented property?","Do you help with subsidy paperwork?"].map(q=><Card key={q}><h3 className="font-bold">{q}</h3><p className="mt-3 text-sm leading-6 text-ink/60">We use the details you share to create an estimate. A free site survey validates the final system design and commercial proposal.</p></Card>)}</div></section>
  <section id="contact" className="bg-lime py-16"><div className="container-wide flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><h2 className="text-4xl font-black tracking-tight">Ready to see your number?</h2><p className="mt-2 text-ink/65">Start with a free, no-obligation estimate.</p></div><Link href="/quote"><Button className="w-fit">Calculate my savings <ArrowUpRight className="ml-1 inline" size={17}/></Button></Link></div></section>
  <footer className="container-wide flex flex-col justify-between gap-4 py-8 text-sm text-ink/60 md:flex-row"><span className="font-black text-ink">caat powerbot.</span><span>Solar, made more human. © 2026</span></footer>
</main> }
